<#
.SYNOPSIS
    Transforms source->app->icon TXT files into icon->srcId+app CSV files.

.DESCRIPTION
    On input:

      <sourceDirectory>:
        1 - <sourceTitle>.txt
        2 - <sourceTitle>.txt
        3 - <sourceTitle>.txt

    On output:

      <destinationDirectory>
        <icon>.csv
        <icon>.csv
        <icon>.csv
        <icon>.csv
        sources.json

    Each text file in the source directory represents a particular source
    media index file, generated by IconToPng.

    Application lines are any lines that are NOT icon lines. They contain the
    title of the application. Application lines are followed by one or more
    icon lines pertaining to that application.

    Icon lines match:

      ^\s{2}([A-Za-z0-9_-]{27}\.png)$

    For each icon line, this tool appends:

      <sourceId>,<currentApplication>

    to:
      <destinationDirectory>\<icon>.csv

    <sourceId> is an id for the source media. If the filename being processed
    is of the form:

        123 - Source Name.txt

    then only "123" is written to the icon CSV files. The mappings from IDs
    to the source titles are written to:

        <destinationDirectory>\sources.json

#>

param(
  [Parameter(Mandatory = $true, Position = 0)]
  [string]$SourceDirectory,

  [Parameter(Mandatory = $true, Position = 1)]
  [string]$DestinationDirectory
)

$iconPattern = '^\s{2}([A-Za-z0-9_-]{27}\.png)$'
$idFilenamePattern = '^(\d+)\s-\s(.+)$'

if (-not (Test-Path -LiteralPath $SourceDirectory)) {
  throw "Source directory does not exist: $SourceDirectory"
}

if (-not (Test-Path -LiteralPath $DestinationDirectory)) {
  New-Item -ItemType Directory -Path $DestinationDirectory | Out-Null
}

# Maps application IDs to full application locations.
$sourceMap = [ordered]@{}

# Since our content is mixed-encoding, use Latin-1 encoding during
# processing to preserve the original bytes

#$latin1 = [System.Text.Encoding]::GetEncoding("ISO-8859-1")

$latin1 = [System.Text.Encoding]::GetEncoding(28591)

Get-ChildItem -LiteralPath $SourceDirectory -Filter *.txt -File | ForEach-Object {

  $fullSource = $_.BaseName

  if ($fullSource -match $idFilenamePattern) {
    $source = $Matches[1]
    $sourceMap[$Matches[1]] = $Matches[2]
  }
  else {
    $source = $fullSource
  }

  $currentApplication = $null

  Write-Host "Processing $fullSource..."

  # In PowerShell 7, I could use:
  #      Get-Content -LiteralPath $_.FullName -Encoding Latin1 | ForEach-Object {
  # Instead of the next two lines

  $text = [System.IO.File]::ReadAllText($_.FullName, $latin1)
  $text -split "\r\n|\r|\n" | ForEach-Object {
    $line = $_.TrimEnd()

    if ($line -match $iconPattern) {

      if ($null -eq $currentApplication) {
        Write-Warning "Icon found before any application in '$($_.Name)': $line"
        return
      }
      $iconFile = $Matches[1].Trim();
      $DestinationDirectory = Resolve-Path -LiteralPath $DestinationDirectory
      $outputFile = Join-Path $DestinationDirectory ($iconFile -replace '\.png$', '.csv')

      # In PowerShell 7, I could use:
      # Add-Content -LiteralPath $outputFile -Encoding Latin1 -Value "$source,$currentApplication"
      [System.IO.File]::AppendAllText(
        $outputFile,
        "$source,$currentApplication`r`n",
        $latin1
      )
    }
    else {
      # Treat every non-icon line as an application line.
      $currentApplication = $line
    }
  }
}

# Write the source index if any IDs were encountered.
if ($sourceMap.Count -gt 0) {
  $sourcesPath = Join-Path $DestinationDirectory "sources.json"

  $sourceMap |
    ConvertTo-Json -Depth 2 |
    Set-Content -LiteralPath $sourcesPath -Encoding UTF8

  Write-Host "Wrote application index to $sources"
}

Write-Host "Done."
Read-Host -Prompt "Press Enter to continue"